services:

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure
  wordpress:
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_files:/var/www/html
networks:
    inception:
        driver: bridge
volumes:
  mariadb_data:
  wordpress_files: