services:

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always
  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    # volumes:
    #   - ./requirements/nginx/conf/:/etc/nginx/http.d/
    #   - ./requirements/nginx/tools:/etc/nginx/ssl/
    #   - wp-volume:/var/www/
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file: .env
    # volumes:
    #   - wordpress:/var/www/
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
networks:
    inception:
        driver: bridge